"""Install and run the OnlyOffice infrastructure for chat mode.

``crewhall office setup`` is the one command that works from any installation
(not only a git checkout): it makes sure Docker is present and running, writes
the Document Server compose file under the state directory, starts it, waits
for health, points crewhall at it (settings) and enables the Web frontends the
container needs. It is idempotent.

The container is reached by crewhall through a base URL the container can use:
the Tailscale IP when available (also reachable by the browser), otherwise the
Docker bridge gateway (with a Web listener on all interfaces).
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from typing import Any

from . import paths, settings

COMPOSE = """# Generated by `crewhall office setup`. Safe to keep under version control off.
services:
  onlyoffice:
    # Pinned on purpose: a floating tag can silently change between deploys and
    # break the integration. Bump it deliberately (and re-run `office setup`).
    image: onlyoffice/documentserver:8.1.3
    container_name: crewhall-onlyoffice
    restart: unless-stopped
    # Default bridge (docker0, 172.17.0.0/16): its gateway is stable and is the
    # one the firewall/UFW rule targets. A compose-created network would use a
    # random 172.x gateway the host does not listen on.
    network_mode: bridge
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - JWT_HEADER=Authorization
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    ports:
      - "__BIND__:__PORT__:80"
    volumes:
      - ./data:/var/www/onlyoffice/Data
      - ./lib:/var/lib/onlyoffice
      - ./logs:/var/log/onlyoffice
"""


class SetupError(RuntimeError):
    pass


def setup_dir() -> str:
    path = os.path.join(paths.state_dir(), "onlyoffice")
    os.makedirs(path, mode=0o700, exist_ok=True)
    return path


def _env_file() -> str:
    return os.path.join(setup_dir(), ".env")


def _compose_file() -> str:
    return os.path.join(setup_dir(), "docker-compose.yml")


def _read_secret() -> str | None:
    try:
        with open(_env_file(), encoding="utf-8") as fh:
            for line in fh:
                if line.startswith("ONLYOFFICE_JWT_SECRET="):
                    return line.split("=", 1)[1].strip() or None
    except OSError:
        return None
    return None


def _ensure_secret() -> str:
    secret = _read_secret()
    if secret:
        return secret
    import secrets as _secrets

    secret = _secrets.token_hex(32)
    fd = os.open(_env_file(), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(f"ONLYOFFICE_JWT_SECRET={secret}\n")
    return secret


def _run(argv: list[str], *, cwd: str | None = None, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(argv, cwd=cwd, check=check, text=True,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT)


def _docker_reachable(prefix: list[str]) -> bool:
    try:
        return subprocess.run([*prefix, "info"], stdout=subprocess.DEVNULL,
                              stderr=subprocess.DEVNULL, timeout=15).returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def _docker_prefix() -> list[str]:
    if _docker_reachable(["docker"]):
        return ["docker"]
    if shutil.which("sudo") and _docker_reachable(["sudo", "-n", "docker"]):
        return ["sudo", "docker"]
    # Interactive sudo: the user runs this in a terminal, so it can prompt.
    if shutil.which("sudo") and sys.stdin.isatty():
        return ["sudo", "docker"]
    raise SetupError(
        "Docker is not reachable. Add your user to the docker group "
        "(`sudo usermod -aG docker $USER`, then log out and back in) or run "
        "this command in a terminal where sudo can ask for the password."
    )


def _install_docker(prefix: list[str]) -> None:
    """Best effort: install Docker with the system package manager."""
    if shutil.which("docker"):
        return
    if not shutil.which("sudo") and os.geteuid() != 0:
        raise SetupError("Docker is not installed and sudo is unavailable")
    root = [] if os.geteuid() == 0 else ["sudo"]
    if shutil.which("apt-get"):
        _run([*root, "apt-get", "update", "-y"])
        _run([*root, "apt-get", "install", "-y", "docker.io"], check=False)
        _run([*root, "apt-get", "install", "-y", "docker-compose-v2"], check=False)
    elif shutil.which("dnf"):
        _run([*root, "dnf", "install", "-y", "docker", "docker-compose-plugin"])
    elif shutil.which("pacman"):
        _run([*root, "pacman", "-Sy", "--noconfirm", "docker", "docker-compose"])
    else:
        raise SetupError("install Docker manually: https://docs.docker.com/engine/install/")


def _start_docker(prefix: list[str]) -> None:
    if _docker_reachable(prefix):
        return
    root = [] if os.geteuid() == 0 else ["sudo"]
    if shutil.which("systemctl"):
        _run([*root, "systemctl", "enable", "--now", "docker"], check=False)
    elif shutil.which("service"):
        _run([*root, "service", "docker", "start"], check=False)


def _tailscale_ip() -> str | None:
    try:
        from .web import tailscale

        if tailscale.available():
            return tailscale.local_ipv4()
    except Exception:  # noqa: BLE001
        return None
    return None


def _ufw_active() -> bool:
    try:
        out = subprocess.run(["systemctl", "is-active", "ufw"], stdout=subprocess.PIPE,
                             stderr=subprocess.DEVNULL, text=True, timeout=5)
        return out.stdout.strip() == "active"
    except (OSError, subprocess.SubprocessError):
        return False


def _ingress_ifaces() -> list[str]:
    """Interfaces a browser can reach the host on (the DS port is published there).

    The Tailscale interface first (the recommended path), then whatever carries
    the default route. Used to let UFW forward browser -> container traffic.
    """
    ifaces: list[str] = []
    if os.path.exists("/sys/class/net/tailscale0"):
        ifaces.append("tailscale0")
    try:
        out = subprocess.run(["ip", "route", "show", "default"], capture_output=True,
                             text=True, timeout=5)
        for line in out.stdout.splitlines():
            parts = line.split()
            if "dev" in parts:
                iface = parts[parts.index("dev") + 1]
                if iface not in ifaces:
                    ifaces.append(iface)
    except (OSError, subprocess.SubprocessError):
        pass
    return ifaces


def _allow_docker_firewall(prefix: list[str], log=print) -> None:
    """Open the firewall for both directions of the OnlyOffice integration.

    Two different UFW policies get in the way:

    - the default INPUT policy drops traffic arriving on ``docker0``, so the
      Document Server cannot fetch documents or post callbacks to crewhall
      (``ufw allow in on docker0``);
    - the default FORWARD policy drops the *published* port, so a browser can
      reach crewhall on 8765 but not the container on 8081. Forwarding from the
      ingress interface to ``docker0`` must be allowed explicitly.

    All rules are idempotent.
    """
    if not shutil.which("ufw") or not _ufw_active():
        return
    root = [] if os.geteuid() == 0 else ["sudo"]

    def ufw(*args: str) -> subprocess.CompletedProcess:
        return _run([*root, "ufw", *args], check=False)

    def changed(result: subprocess.CompletedProcess) -> bool:
        text = (result.stdout or "").lower()
        return result.returncode == 0 and "skipping" not in text and "already exists" not in text

    if changed(ufw("allow", "in", "on", "docker0")):
        log("Allowed the Docker bridge in UFW (container -> crewhall).")
    for iface in _ingress_ifaces():
        if changed(ufw("route", "allow", "in", "on", iface, "out", "on", "docker0")):
            log(f"Allowed UFW forwarding {iface} -> docker0 (browser -> OnlyOffice).")


def _bridge_gateway(prefix: list[str]) -> str:
    try:
        out = _run([*prefix, "network", "inspect", "bridge",
                    "-f", "{{(index .IPAM.Config 0).Gateway}}"], check=False)
        gw = (out.stdout or "").strip().splitlines()
        if gw and gw[0]:
            return gw[0]
    except (OSError, subprocess.SubprocessError):
        pass
    return "172.17.0.1"


def _probe_host(bind: str | None) -> str:
    """The address to probe for health from this host, for a given bind host.

    When the Document Server binds a specific address (e.g. the Tailscale IP) it
    is *not* reachable on loopback, so probing 127.0.0.1 would always fail. A
    wildcard bind is probed on loopback.
    """
    host = (bind or "").strip()
    if host in ("", "0.0.0.0", "::", "[::]", "*"):
        return "127.0.0.1"
    return host


def _wait_health(port: int, host: str = "127.0.0.1", timeout: float = 300.0) -> bool:
    deadline = time.monotonic() + timeout
    url = f"http://{_probe_host(host)}:{port}/healthcheck"
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=3) as resp:
                if resp.status == 200:
                    return True
        except (urllib.error.URLError, OSError):
            pass
        time.sleep(2)
    return False


def _tailscale_dns() -> str | None:
    try:
        from .web import tailscale

        if tailscale.available():
            return tailscale.dns_name()
    except Exception:  # noqa: BLE001
        return None
    return None


def web_port() -> int:
    """The port the Web UI (and thus crewhall) listens on."""
    try:
        from . import settings

        return int(settings.get("web.port") or 8765)
    except Exception:  # noqa: BLE001
        return 8765


def connection_plan(
    port: int,
    bind: str | None,
    *,
    ts_ip: str | None,
    dns: str | None,
    bridge_gw: str,
    crewhall_port: int,
) -> dict[str, str]:
    """Decide how the browser reaches the DS and how the DS reaches crewhall.

    Tailscale is preferred because a single address satisfies both directions:
    the DS binds the tailnet IP (reachable from the browser and usable as the
    ``office.base_url`` the container calls back into). Without Tailscale the
    browser uses loopback and the container reaches crewhall through the Docker
    bridge gateway, which only works if crewhall listens on an interface the
    container can reach (the manual ``crewhall web --host 0.0.0.0`` path).
    """
    explicit = bind if bind not in (None, "", "auto") else None
    if ts_ip:
        host = explicit or ts_ip
        public_host = dns or ts_ip
        return {
            "bind": host,
            "public_url": f"http://{public_host}:{port}",
            "base_url": f"http://{ts_ip}:{crewhall_port}",
        }
    host = explicit or "127.0.0.1"
    return {
        "bind": host,
        "public_url": f"http://{host}:{port}",
        "base_url": f"http://{bridge_gw}:{crewhall_port}",
    }


def _setup_external(url: str, jwt_secret: str | None, *, log=print) -> dict[str, Any]:
    """Point crewhall at an already-running Document Server (no Docker here)."""
    url = url.rstrip("/")
    if not url:
        raise SetupError("--external needs the Document Server base URL")
    base = str(settings.get("web.public_url") or "").rstrip("/")
    patch: dict[str, Any] = {
        "office.enabled": True,
        "office.public_url": url,
        "office.base_url": base,
        "office.jwt_enabled": True,
        "office.collab_enabled": True,
    }
    if jwt_secret:
        patch["office.jwt_secret"] = jwt_secret
    settings.patch(patch)
    log(f"office.public_url = {url}")
    log(f"office.base_url    = {base or '(unset: set web.public_url so the DS can call back)'}")
    healthy = _healthcheck(url)
    return {"port": None, "base_url": base, "public_url": url, "healthy": healthy,
            "tailscale": bool(_tailscale_ip()), "secret_set": bool(jwt_secret or _read_secret()),
            "external": True}


def setup(*, port: int = 8081, bind: str | None = None, external: str | None = None,
          jwt_secret: str | None = None, wait: bool = True, log=print) -> dict[str, Any]:
    if external:
        return _setup_external(external, jwt_secret, log=log)

    prefix = _docker_prefix() if shutil.which("docker") else None
    if prefix is None:
        log("Docker not found; installing…")
        _install_docker([])
        prefix = _docker_prefix()
    _start_docker(prefix)
    prefix = _docker_prefix()

    ts_ip = _tailscale_ip()
    plan = connection_plan(port, bind, ts_ip=ts_ip, dns=_tailscale_dns(),
                           bridge_gw=_bridge_gateway(prefix), crewhall_port=web_port())

    secret = _ensure_secret()
    with open(_compose_file(), "w", encoding="utf-8") as fh:
        fh.write(COMPOSE.replace("__BIND__", plan["bind"]).replace("__PORT__", str(port)))

    log("Starting the OnlyOffice Document Server (first run pulls the image)…")
    result = _run([*prefix, "compose", "-f", _compose_file(), "--env-file", _env_file(),
                   "up", "-d"], cwd=setup_dir(), check=False)
    if result.returncode != 0:
        raise SetupError("docker compose failed:\n" + (result.stdout or ""))

    healthy = True
    if wait:
        log("Waiting for the Document Server to be healthy…")
        healthy = _wait_health(port, plan["bind"])
        if not healthy:
            # A stale container from a previous deploy is the common cause: restart
            # it once and give it another chance instead of failing the install.
            log("Not healthy yet; restarting the container and waiting again…")
            _run([*prefix, "compose", "-f", _compose_file(), "--env-file", _env_file(),
                  "restart"], cwd=setup_dir(), check=False)
            healthy = _wait_health(port, plan["bind"])
        if not healthy:
            raise SetupError("OnlyOffice did not answer /healthcheck in time; "
                             "check `docker logs crewhall-onlyoffice`")

    # The Document Server must reach crewhall: open the firewall for the bridge.
    _allow_docker_firewall(prefix, log=log)

    settings.patch({
        "office.enabled": True,
        "office.public_url": plan["public_url"],
        "office.base_url": plan["base_url"],
        "office.jwt_enabled": True,
        "office.jwt_secret": secret,
        "office.collab_enabled": True,
    })
    log(f"office.public_url = {plan['public_url']}")
    log(f"office.base_url  = {plan['base_url']}")
    if not ts_ip:
        log("warning: no Tailscale detected; the container reaches crewhall through "
            "the Docker gateway, so crewhall must listen on an interface the container "
            "can reach (or set office.base_url to one). Run `crewhall doctor` to verify.")

    # Frontends the container needs: local + tailscale when available.
    try:
        from .client import Client

        mode = "both" if ts_ip else "local"
        Client().call("frontend_set", mode=mode)
        log(f"Web frontends set to '{mode}'.")
    except Exception as exc:  # noqa: BLE001 - setup must not fail on this
        log(f"(could not set frontends automatically: {exc})")

    return {"port": port, "base_url": plan["base_url"], "public_url": plan["public_url"],
            "healthy": healthy, "tailscale": bool(ts_ip), "secret_set": True}


def _healthcheck(url: str, timeout: float = 5.0) -> bool:
    try:
        with urllib.request.urlopen(f"{url.rstrip('/')}/healthcheck", timeout=timeout) as resp:
            return resp.status == 200
    except (urllib.error.URLError, OSError):
        return False


def status() -> dict[str, Any]:
    prefix = None
    for candidate in (["docker"], ["sudo", "-n", "docker"]):
        if _docker_reachable(candidate):
            prefix = candidate
            break
    info: dict[str, Any] = {"docker": bool(prefix), "compose": os.path.exists(_compose_file())}
    if prefix:
        out = _run([*prefix, "ps", "--filter", "name=crewhall-onlyoffice",
                    "--format", "{{.Status}}"], check=False)
        info["container"] = (out.stdout or "").strip() or None
        gw = _bridge_gateway(prefix)
        info["bridge_gateway"] = gw
    info["tailscale_ip"] = _tailscale_ip()
    info["office_enabled"] = bool(settings.get("office.enabled"))
    info["office_base_url"] = settings.get("office.base_url")
    info["office_public_url"] = settings.get("office.public_url")
    public = str(info["office_public_url"] or "")
    info["healthy"] = _healthcheck(public) if public else False
    return info
